<?php
return [
    'POST /api/login' => true,
    'GET /api/logout' => true,
    'POST /api/register' => true,
    'POST /api/password/recover' => true,
    'POST /api/password/reset' => true,
    'GET /api/eventos' => true,
    'POST /api/eventos/admin' => true,
    'GET /api/eventos/admin' => true,
    'GET /api/carreras' => true,
    'POST /api/carreras' => true,
    'GET /api/carreras/metodos' => true,
    'POST /api/carreras/metodos' => true,
    'GET /api/productos' => true,
    'POST /api/productos' => true,
    'PUT /api/productos' => true,
    'DELETE /api/productos' => true,
    'GET /api/productos/paginados' => true,
    'DELETE /api/productos/paginados' => true,
    'GET /api/usuarios' => true,
    'POST /api/usuarios' => true,
    'DELETE /api/usuarios' => true,
    'GET /api/profile' => true,
    'GET /api/participar' => true,
    'POST /api/participar' => true,
    'GET /api/participaciones' => true,
    'POST /api/participaciones/eliminar' => true,
    'GET /api/rutas' => true,
    'POST /api/rutas' => true,
    'GET /api/categorias-tipos' => true
];
